(specifications->manifest
  (list 
    	"m4"
        "autoconf"
        "bison"
        "flex"
        "make"
        "git"
	"mercurial"
        "pkg-config"
    	"gcc-toolchain"
	"clang-toolchain"
        "llvm"
	"libstdc++-doc"
	))
